- name: Install Docker
  yum:
    name:
      - docker
    state: present

- name: Start Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Create project folder
  file:
    path: "{{ db_project_dir }}"
    state: directory

- name: Copy docker-compose template
  template:
    src: docker-compose.yml.j2
    dest: "{{ db_project_dir }}/docker-compose.yml"

- name: Copy healthchecks folder
  copy:
    src: healthchecks/
    dest: "{{ db_project_dir }}/healthchecks/"
    mode: "0755"

- name: Start DB container
  command: docker compose up -d
  args:
    chdir: "{{ db_project_dir }}"
