$ANSIBLE_VAULT;1.1;AES256
32666437323530336465333635396634343434343139323336373464653735343265393033356133
3365633861326566366262393935643434303432346434380a346533323735343836643366323136
35316237353530363832623062643539336337616339646365356133366138393833323665363330
3833643062346238320a386366323963326630343665323931623066373762306262383931376430
62663439663963613766643966346337326634396165616130666538633933633661353333386639
61623664363865653965316632633538396465366339393930363466623832323063626163346332
63336566333265376262343833663533376562643539303166373933323362636437376565613866
34663532356233666536373961633833396362636235393533306532633062366633366161353835
30613634616264396264666139343935383461336136333263326566633966666562356439663437
32366635643238303734313230633131313763663866663261386164306330363033383339653936
663162623364316536363839333165313137
