$ANSIBLE_VAULT;1.1;AES256
38316466636630643037623665313330613133353536336164636635613366386330373037623138
6264333365373063353738653464353466336439383931610a373034663836666433643965663637
62306336343565346130636633646435303561383537666263366263666566323637623730326130
3363663563333531650a643230653331346562383534623363396337376164363434623837323961
62383061653133343437396139313261323234326165373162636561306135663738623837356265
31626130366431336366613039323330306161313232356530326264653538306663623261336637
36386464303938376464373935656564373536636534366539346262353463313238663866633032
63633430643864663966316237313365663530376632363966316465633931393334396234633338
30623339363330623133633363646262346338313632636334663738656464633566346434346537
37373135646130373364316164303565646361376266633266326461656164313133613231383961
62656538316665323563363838626166303739303639343930383734623666383866616364393037
38333965663238313134653830653964386562396339666430633231326134353361366264643436
37316466633238636233666233626466306566353034343566393834376261373339
