services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - "./healthchecks:/healthchecks"
    healthcheck:
      test: ["CMD", "sh", "/healthchecks/redis.sh"]
      interval: "5s"

  worker:
    image: mrrobofliper/mvp-worker:latest
    depends_on:
      redis:
        condition: service_healthy

