services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - "./healthchecks:/healthchecks"
    healthcheck:
      test: ["CMD", "sh", "/healthchecks/redis.sh"]
      interval: "5s"

  worker:
    image: mrrobofliper/mvp-worker:latest
    env_file:
      - .env
    environment:
      ConnectionStrings__Default: "Host=${DB_HOST};Port=${DB_PORT};Username=${DB_USER};Password=${DB_PASSWORD};Database=${DB_NAME}"
    depends_on:
      redis:
        condition: service_healthy

